{{ config(
    materialized='table',
    alias='por_profesion'
) }}

SELECT COUNT(*) CANTIDAD , NIVEL FROM(
SELECT 
    CONCAT(NOMBRE, ' ',
    IFNULL(NULLIF(TRIM(APELLIDO_PATERNO, ''), ''), ' '),
    IFNULL(NULLIF(TRIM(APELLIDO_MATERNO, ''), ''), ' ')) AS CANTIDAD,
    NIVEL,

FROM 
    DBT_DATABASE.DBT_SCHEMA.BECAS
) AS NOMBRE_CONCATENADO
GROUP BY NOMBRE_CONCATENADO.NIVEL
LIMIT 3