{{ config(
    materialized='table',
    alias='por_profesion'
) }}

SELECT COUNT(*) CANTIDAD , NIVEL FROM(
SELECT 
    CONCAT(NOMBRE, ' ',APELLIDO_PATERNO, ' ',APELLIDO_MATERNO) AS CANTIDAD,
    NIVEL,

FROM 
     {{ source('DBT_SCHEMA', 'BECAS') }}
) AS NOMBRE_CONCATENADO
GROUP BY NOMBRE_CONCATENADO.NIVEL
LIMIT 3