{{ config(materialized="table", alias="comparativa_x_genero") }}

SELECT 
    AREA_DE_CONOCIMIENTO,
    SUM(CASE WHEN GENERO = 'M' THEN 1 ELSE 0 END) AS HOMBRES,
    SUM(CASE WHEN GENERO = 'F' THEN 1 ELSE 0 END) AS MUJERES,
    ROUND(100.0 * SUM(CASE WHEN GENERO = 'M' THEN 1 ELSE 0 END) / COUNT(*), 2) AS PORCENTAJE_HOMBRES,
    ROUND(100.0 * SUM(CASE WHEN GENERO = 'F' THEN 1 ELSE 0 END) / COUNT(*), 2) AS PORCENTAJE_MUJERES
FROM 
    from {{ source("DBT_SCHEMA", "BECAS") }}
WHERE AREA_DE_CONOCIMIENTO IS NOT NULL
GROUP BY 
    AREA_DE_CONOCIMIENTO