SELECT 
    YEAR,
    MONTH,
    PRICE_WHEAT_TON,
    PRICE_RICE_TON,
    PRICE_CORN_TON,
    INFLATION_RATE,
    PRICE_WHEAT_TON_INFL,
    PRICE_RICE_TON_INFL,
    PRICE_CORN_TON_INFL
FROM {{ source('DBT_SCHEMA', 'NEW_RICE') }}
LIMIT 5;