{{ config(
    materialized='table',
    alias='TOTAL_PRICES'
) }}

SELECT 
    YEAR, 
    SUM(PRICE_WHEAT_TON) AS TOTAL_PRICE_WHEAT,
    SUM(PRICE_RICE_TON) AS TOTAL_PRICE_RICE
FROM 
    DBT_DATABASE.DBT_SCHEMA.NEW_RICE
GROUP BY YEAR
ORDER BY YEAR ASC