version: 2

sources:
  - name: DBT_SCHEMA  # Este es un nombre lógico para referenciar tu fuente
    schema: DBT_SCHEMA  # El esquema real en Snowflake
    database: DBT_DATABASE  # La base de datos en Snowflake
    tables:
      - name: BECAS  # El nombre d